---

- name: "Execute eigrp_role to configure EIGRP Stuff"
  hosts: r1
  gather_facts: false
  connection: network_cli

  roles:
    - eigrp_role

  tasks:
    - name: "FURTHER VERIFY"
      cisco.ios.ios_command:
        commands:
          - "show ip eigrp interface"
      register: new_output

    - name: "Print verification"
      debug:
        msg: "{{ new_output }}"
