all:
  hosts:
  children:
    routers:
      children:
        usa:
          vars:
            ansible_user: r31mong
            ansible_ssh_pass: SantosB5L18#!
            ansible_become_pass: SantosB5L18#!
            ansible_network_os: ios
            ansible_connection: network_cli
            ansible_become_method: enable
          hosts:
            r1:
              ansible_host: 192.168.1.81
        uk:
          vars:
            ansible_user: r31mong
            ansible_ssh_pass: SantosB5L18#!
            ansible_become_pass: SantosB5L18#!
            ansible_network_os: ios
            ansible_connection: network_cli
            ansible_become_method: enable
          hosts:
            r2:
              ansible_host: 192.168.1.82
        asia:
          vars:
            ansible_user: r31mong
            ansible_ssh_pass: SantosB5L18#!
            ansible_become_pass: SantosB5L18#!
            ansible_network_os: ios
            ansible_connection: network_cli
            ansible_become_method: enable
          hosts:
            r3:
              ansible_host: 192.168.1.83