---

- name: "Play to configure EIGRP Stuff"
  hosts: r1
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "TASK1 - Push EIGRP"
      cisco.ios.ios_config:
        src: "eigrp.j2"
      notify: eigrp_handler_example
      register: eigrp_result

    - name: "TASK3 - Verify EIGRP Config"
      cisco.ios.ios_command:
        commands:
          - "show run | section eigrp"
      register: show_eigrp_result

    - name: "TASK2 - print EIGRP Configs"
      debug:
       msg: "{{ show_eigrp_result.stdout_lines }}"
  
  handlers:
    - name: eigrp_handler_example
      debug:
        msg: "{{ eigrp_result.commands }}"
