- name: "Play 1: Test Playbook - Capture Date time"
  hosts: localhost
  
  tasks:
    - name: "Task 1: Collect facts about local hosts - Date Time"
      ansible.builtin.setup:
        filter:
          - "ansible_date_time"

    - name: "Task 2: Recording Variable"
      set_fact:
        TD: "{{ ansible_date_time.date }}"

    - name: "Task 3 of Play 1: Creating directories"
      file: 
        path: "Backups/{{ TD }}"
        state: directory
      run_once: true

- name: "Play 2: Backing Up Configurations"
  hosts: Router
  connection: network_cli

  tasks:
    - name: "Task 1 of Play 2: Pull Configurations from Remote Devices"
      napalm_get_facts:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        dev_os: "{{ napalm_platform }}"
        filter: ["config"]
      register: result
    
    - name: "Task 2 of Play 2: Print result"
      debug:
        msg: "{{ result }}"
